spring.application.name=backend_api
spring.application.version=0.1.0

# H2-Datenbank (in-memory)
spring.datasource.url=jdbc:h2:mem:recipe_book
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2-Konsole (Browser-Zugriff: http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JsonWebToken
security.jwt.token-secret=${token-secret:#{'NotSoSecretTokenForDevelopmentPurposes'}}

security.seeder.admin-password=${admin-password:#{'admin-password'}}
security.seeder.demo-password=${demo-password:#{'demo-password'}}