### Valid registration
POST localhost:8080/auth/register
Content-Type: application/json

{
  "username": "testUser",
  "password": "testPassword",
  "email": "test.mail@mail.de"
}

> {%
    client.test("Register Successful, JWT Token Retrieved, Correct Username", function () {
        client.assert(response.status == 201, "Wrong response status");
        client.assert(response.body.jwtToken, "Missing JWT Token");
        client.assert(response.body.username == "testUser", "Wrong Username");
    });
%}

### Valid login
POST localhost:8080/auth/login
Content-Type: application/json

{
  "username": "testUser",
  "password": "testPassword"
}

> {%
    client.test("Register Successful, JWT Token Retrieved, Correct Username", function () {
        client.assert(response.status == 200, "Wrong response status");
        client.assert(response.body.jwtToken, "Missing JWT Token");
        client.assert(response.body.username == "testUser", "Wrong Username");
    });
%}

### Wrong password in login
POST localhost:8080/auth/login
Content-Type: application/json

{
  "username": "testUser",
  "password": "password"
}

> {%
    client.test("Register Successful, JWT Token Retrieved, Correct Username", function () {
        client.assert(response.status == 400, "Wrong response status");
        client.assert(response.body.detail == "Wrong password", "Missing JWT Token");
        client.assert(response.body.title == "Wrong Password", "testUser");
    });
%}